### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'raw_data/ogbg_moltoxcast/raw/assays.csv.gz'

### ISSUE THREAD

**Issue by TousenKaname** [liugangcode/InfoAlign#1]
Hi!
Thanks for your excellent work! :)
I encountered a issue when I run the command ` python main.py --model-path ckpt/pretrain.pt --dataset finetune-moltoxcast`. I found that we need to redownload the dataset and then missed assays.csv.gz data. Do you know the reason thy this happen?
Thanks!

**Comment by liugangcode** [comment]
Thank you for your interest and for reaching out. Are you referring to this line? [Link to code](https://github.com/liugangcode/InfoAlign/blob/2b78137e325836f383852ac5a61f5f2251afb7b8/utils/misc.py#L61).

If so, please check if the `mol.csv.gz` file is located in the `ogbg_moltoxcast/mapping` folder. A temporary solution is to rename this file to `assays.csv.gz` and move it to the `raw` folder.

**Comment by TousenKaname** [comment]
Thanks for your help! You saved me a lot of time.
I finetune moltoxcast successfully by your method. But where can I download the  `assays.csv.gz` file?

**Comment by liugangcode** [comment]
The assays file is provided in the repository for the other three datasets. For ToxCast, it is the mol.csv.gz file, so you don’t need to download it from other sources. I will update the code to resolve this issue.

**Comment by TousenKaname** [comment]
Thanks for your help!
